import turtle
import math
import tkinter

def logSpiral():
    turtle.title("Логарифмічна спіраль")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(1, 52):
        a=10*3.14*(i-1)/100
        exp=2.71**(0.2*a)
        r=5*exp
        x=r*math.cos(a)
        y=r*math.sin(a)
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def archSpiral():
    turtle.title("Архімедова спіраль")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(1, 252):
        a=10*3.14*(i-1)/100
        x=a*math.cos(0.5*a)
        y=a*math.sin(0.5*a)
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def pascRavlkik():
    turtle.title("Равлик Паскаля")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(1, 42):
        a=2*3.14*(i-1)/40
        r=80-150*math.cos(a)
        x=r*math.cos(a)
        y=r*math.sin(a)
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def linChrest():
    turtle.title("Лінія 'Хрест'")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(1, 202):
        a=2*3.14*(i-1)/200
        c=math.sin(2*a)
        if c!=0:
            r=50/c
            x=r*math.cos(a)
            y=r*math.sin(a)
            if y == -817.0229336721669 or x == -838.8436203249894 or y == 861.8624062913411:
                turtle.penup()
            turtle.goto(x,y)
            turtle.pendown()
    turtle.exitonclick()

def locAniezy():
    turtle.title("Локон Анієзи")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(-50, 52):
        a=5*i
        x=a
        y=240000/(a**2 + 5000)
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def conNihomeda():
    turtle.title("Конхоїда Ніхомеда")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(-100, 102):
        a=2*i
        if (a-10)**2!= 0:
            d=3600*a**2/(a-10)**2 - a**2
            if d>=0:
                x=a
                y=d**0.5
                turtle.goto(x,y)
                turtle.pendown()
    turtle.penup()
    for i in range(-100, 102):
        a=2*i
        if (a-10)**2 != 0:
            d=3600*a**2/(a-10)**2 - a**2
            if d>=0:
                x=a
                y=-d**0.5
                turtle.goto(x,y)
                turtle.pendown()
    turtle.exitonclick()

def linLantsuga():
    turtle.title("Лінія ланцюга")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(-100, 102):
        a=5*i
        x=a
        y=-30*(math.exp(a/30)-math.exp(-a/30))/2
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def astroida():
    turtle.title("Астроїда")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(1, 202):
        a=20*3.14*i
        x=70*math.cos(a)**3
        y=-70*math.sin(a)**3
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def lysDecarta():
    turtle.title("Листок Декарта")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(-200, 202):
        a=i/10
        d=a**3+1
        if d!=0:
            x=90*a/d
            y=-90*a**2/d
            turtle.goto(x,y)
            turtle.pendown()
    turtle.exitonclick()

def tsycloida():
    turtle.title("Циклоїда")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(-100, 102):
        a=3.14*i/10
        x=15*a+20*math.sin(a)
        y=-15+20*math.cos(a)
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def linGraphic():
    turtle.title("Лінійний графік: y=ax+b")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    a=float(input("a?"))
    b=float(input("b?"))
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(-10, 11):
        x=(i-b)/a*50
        y=i*50
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def parabola():
    turtle.title("Парабола: y=ax*х+b")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    a=float(input("a?"))
    b=float(input("b?"))
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(-50, 51):
        x=i*12.5
        y=(i*i*a+4*b)*12.5
        turtle.goto(x,y)
        turtle.pendown()
    turtle.exitonclick()

def hiberbola():
    turtle.title("Гіпербола: y=a/x+b")
    turtle.hideturtle()
    turtle.setup(500,500)
    turtle.speed(0)
    a=float(input("a?"))
    b=float(input("b?"))
    turtle.bgcolor("white")
    turtle.color("black")
    for i in range(1,10):
        turtle.penup()
        turtle.goto(i*50-250,-250)
        turtle.pendown()
        turtle.goto(i*50-250,250)
        turtle.penup()
        turtle.goto(-250, i * 50 - 250)
        turtle.pendown()
        turtle.goto(250, i * 50 - 250)
    turtle.width(3)
    turtle.penup()
    turtle.goto(-250,0)
    turtle.pendown()
    turtle.goto(250,0)
    turtle.penup()
    turtle.goto(0,-250)
    turtle.pendown()
    turtle.goto(0,250)
    turtle.color("green")
    turtle.penup()
    for i in range(-250, 251):
        if i != 0:
            x=i
            y=(a*10/i)*250+b*50
            if i == 1:
                turtle.penup()
            turtle.goto(x,y)
            turtle.pendown()
    turtle.exitonclick()

window = tkinter.Tk()
window.title("Графіки")
window.geometry("500x700")
button1 = tkinter.Button(window, text="Логарифмічна спіраль", background="gray", command=logSpiral)
button2 = tkinter.Button(window, text="Архімедова спіраль", background="gray", command=archSpiral)
button3 = tkinter.Button(window, text="Равлик Паскаля", background="gray", command=pascRavlkik)
button4 = tkinter.Button(window, text="Лінія 'Хрест'", background="gray", command=linChrest)
button5 = tkinter.Button(window, text="Локон Анієзи", background="gray", command=locAniezy)
button6 = tkinter.Button(window, text="Конхаїда Ніхомеда", background="gray", command=conNihomeda)
button7 = tkinter.Button(window, text="Лінія ланцюга", background="gray", command=linLantsuga)
button8 = tkinter.Button(window, text="Астроїда", background="gray", command=astroida)
button9 = tkinter.Button(window, text="Листок Декарта", background="gray", command=lysDecarta)
button10 = tkinter.Button(window, text="Циклоїда", background="gray", command=tsycloida)
button11 = tkinter.Button(window, text="Лінійний графік з вводом чисел", background="gray", command=linGraphic)
button12 = tkinter.Button(window, text="Парабола з вводом чисел", background="gray", command=parabola)
button13 = tkinter.Button(window, text="Гіпербола з вводом чисел", background="gray", command=hiberbola)
button14 = tkinter.Label(text="Виконано учнем 21-М групи\n Андрієм Дирдою")
button1.place(height=100, width=250, x=0, y=0)
button2.place(height=100, width=250, x=0, y=100)
button3.place(height=100, width=250, x=0, y=200)
button4.place(height=100, width=250, x=0, y=300)
button5.place(height=100, width=250, x=0, y=400)
button6.place(height=100, width=250, x=250, y=0)
button7.place(height=100, width=250, x=250, y=100)
button8.place(height=100, width=250, x=250, y=200)
button9.place(height=100, width=250, x=250, y=300)
button10.place(height=100, width=250, x=250, y=400)
button11.place(height=100, width=250, x=0, y=500)
button12.place(height=100, width=250, x=0, y=600)
button13.place(height=100, width=250, x=250, y=500)
button14.place(height=100, width=250, x=250, y=600)
window.mainloop()